### ISSUE TITLE
Feature maps setting about ECPeNet

### ISSUE THREAD

**Issue by hjbiao09** [csjcai/DBCPeNet#2]
THX for sharing your code!
I've read your paper, it is a great job. But I got some problems with feature maps.
According to your paper, feature maps should be 64 except last and ECPe layer. 
After shuffle downsampling, feature maps increase to 4X64= 256, 4X256=1024. it is much larger than SRN-DeblurNet(32,64,128).
Did I miss understanding your paper? or is it right?
Did you have results in smaller feature maps setting like SRN-DeblurNet?

**Comment by csjcai** [comment]
After shuffle downsampled, the feature maps will be slimmed down by the followed filter (64  output channels).

**Comment by hjbiao09** [comment]
Thank you for your advice!
